const $=s=>document.querySelector(s),content=$('#content'),search=$('#search'),pf=$('#platformFilter'),sf=$('#statusFilter'),stats=$('#stats');
let view='library',library=JSON.parse(localStorage.getItem('gameshelf-library')||'null')||DEFAULT_LIBRARY,dynamicCatalog=[],loadingCatalog=false,searchTimer;
const save=()=>localStorage.setItem('gameshelf-library',JSON.stringify(library));
const baseGame=id=>CATALOG.find(g=>g.id===id),game=id=>baseGame(id)||dynamicCatalog.find(g=>g.id===id)||library.find(x=>x.gameId===id)?.snapshot;
const money=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(n);
const gradients=['linear-gradient(145deg,#102a43,#174d6d 48%,#07131f)','linear-gradient(145deg,#351c4d,#6a315f 50%,#130e1b)','linear-gradient(145deg,#403218,#9b6422 52%,#151006)','linear-gradient(145deg,#1b3b31,#276b57 52%,#081512)','linear-gradient(145deg,#3b1d24,#8a3540 52%,#16090c)','linear-gradient(145deg,#22284b,#4c53a2 52%,#0d1020)'];
const grad=g=>gradients[Math.abs([...(g.id||g.title)].reduce((a,c)=>a+c.charCodeAt(0),0))%gradients.length],initials=t=>t.split(/\s+/).filter(x=>x.length>2).slice(0,4).join(' ');
const steamCover=g=>g.cover|| (g.steamAppId?`https://cdn.cloudflare.steamstatic.com/steam/apps/${g.steamAppId}/library_600x900_2x.jpg`:null),steamHero=g=>g.hero||(g.steamAppId?`https://cdn.cloudflare.steamstatic.com/steam/apps/${g.steamAppId}/library_hero.jpg`:null);
const imgFallback=`this.style.display='none';this.parentElement.classList.add('image-fallback')`;
function stat(l,v){return `<div class="stat"><span>${l}</span><b>${v}</b></div>`}
function renderStats(){stats.innerHTML=[['Giocati',library.filter(x=>x.status==='Giocati').length],['In corso',library.filter(x=>x.status==='In corso').length],['Da giocare',library.filter(x=>x.status==='Da giocare').length],['Totale libreria',library.length]].map(x=>stat(...x)).join('')}
function renderHero(){const playing=library.find(x=>x.status==='In corso'),g=playing?game(playing.gameId):CATALOG[0];if(!g)return;const hero=steamHero(g),cover=steamCover(g),h=$('#hero');h.style.setProperty('--game-gradient',grad(g));h.style.backgroundImage=hero?`linear-gradient(90deg,#090b11f5 0%,#090b11b8 42%,#090b1140 72%,#090b1110),url('${hero}')`:'';h.innerHTML=`<div class="hero-content"><div class="hero-kicker">CONTINUA A GIOCARE</div><h2>${g.title}</h2><p>${g.description||''}</p><div class="hero-meta"><span>${playing?.platform||g.platforms?.[0]||'Videogioco'}</span><span>${g.genres?.[0]||'Game'}</span><span>★ ${g.rating||'—'}/100</span></div></div><div class="hero-art"><div class="hero-cover" style="--game-gradient:${grad(g)}">${cover?`<img src="${cover}" alt="Cover di ${g.title}" onerror="${imgFallback}">`:''}<span>${initials(g.title)}</span></div></div>`;h.onclick=()=>openDetail(g.id)}
function normalizePlatform(p){if(/playstation 5|ps5/i.test(p))return'PS5';if(/nintendo switch/i.test(p))return'Switch 2';if(/pc|linux|mac/i.test(p))return'Steam';return p}
function card(g,e){const prices=Object.values(g.price||{}),platform=e?.platform||normalizePlatform(g.platforms?.[0]||'');const cover=steamCover(g),price=prices.length?`da <b>${money(Math.min(...prices))}</b> · indicativo`:(g.source==='RAWG'?'prezzo live nel dettaglio':'prezzo non disponibile');return `<article class="card" data-id="${g.id}"><div class="game-cover" data-initials="${initials(g.title)}" style="--game-gradient:${grad(g)}">${cover?`<img src="${cover}" alt="Cover di ${g.title}" loading="lazy" onerror="${imgFallback}">`:''}<span class="rating">${g.rating||'—'}</span>${e?`<span class="status-badge">${e.status}</span>`:''}</div><div class="card-body"><div class="title">${g.title}</div><div class="meta">${platform||'—'} · ${g.year||'TBA'}</div><div class="chips">${(g.genres||[]).slice(0,2).map(x=>`<span class="chip">${x}</span>`).join('')}</div><div class="price">${price}</div></div></article>`}
async function loadLiveCatalog(q=''){if(!RawgService.enabled()){dynamicCatalog=[];return}loadingCatalog=true;render();try{dynamicCatalog=await RawgService.list(q)}catch(e){console.error(e);dynamicCatalog=[]}finally{loadingCatalog=false;render()}}
function currentRows(){if(view==='catalog')return (RawgService.enabled()?dynamicCatalog:CATALOG).map(g=>({g,entry:library.find(x=>x.gameId===g.id)}));let lib=view==='wishlist'?library.filter(x=>x.status==='Da giocare'):library;return lib.map(entry=>({g:game(entry.gameId),entry}))}
function render(){renderHero();renderStats();let rows=currentRows();const q=search.value.toLowerCase();if(view!=='catalog'||!RawgService.enabled())rows=rows.filter(({g})=>g&&(!q||g.title.toLowerCase().includes(q)||(g.developer||'').toLowerCase().includes(q)));rows=rows.filter(({g,entry})=>g&&(pf.value==='all'||(entry?entry.platform:(g.platforms||[]).some(p=>normalizePlatform(p)===pf.value)))&&(sf.value==='all'||(entry&&entry.status===sf.value)));content.innerHTML=loadingCatalog?`<div class="empty">Caricamento catalogo reale…</div>`:rows.length?rows.map(({g,entry})=>card(g,entry)).join(''):`<div class="empty">${view==='catalog'&&!RawgService.enabled()?'Catalogo demo. Configura una RAWG API key da ⚙ per attivare il catalogo reale.':'Nessun gioco trovato.'}</div>`;$('#resultCount').textContent=`${rows.length} ${rows.length===1?'gioco':'giochi'}`;$('#sectionTitle').textContent=view==='catalog'?'Scopri nuovi giochi':view==='wishlist'?'La tua wishlist':'I tuoi giochi';$('#sourceNote').innerHTML=view==='catalog'&&RawgService.enabled()?'Dati catalogo e immagini forniti da <a href="https://rawg.io" target="_blank" rel="noopener">RAWG</a>.':'';document.querySelectorAll('.card').forEach(c=>c.onclick=()=>openDetail(c.dataset.id))}
function fmtProviderPrice(p){if(!p)return null;const price=p.price||p;const amount=price.amount??price.amountInt/100;return Number.isFinite(amount)?`${amount.toFixed(2).replace('.',',')} ${price.currency||'EUR'}`:null}
async function hydrateRawg(g){if(!g?.rawgId)return g;try{const full=await RawgService.detail(g.rawgId);dynamicCatalog=dynamicCatalog.map(x=>x.id===g.id?full:x);const entry=library.find(x=>x.gameId===g.id);if(entry){entry.snapshot=full;save()}return full}catch{return g}}
async function loadLivePrice(g){const box=$('#livePrice');if(!box)return;if(!PriceService.enabled()){box.innerHTML='<small>Prezzi live PC</small><span>Configura IsThereAnyDeal da ⚙</span>';return}box.innerHTML='<small>Prezzi live PC</small><span>Caricamento…</span>';try{const x=await PriceService.current(g.title);const cur=fmtProviderPrice(x?.current?.price||x?.current),low=fmtProviderPrice(x?.historyLow?.price||x?.historyLow);box.innerHTML=x?`<small>IsThereAnyDeal · Italia</small><b>${cur||'N/D'}</b>${low?`<span> · minimo storico ${low}</span>`:''}${x.url?`<a href="${x.url}" target="_blank" rel="noopener">Vedi offerta</a>`:''}`:'<small>IsThereAnyDeal</small><span>Nessun prezzo trovato</span>'}catch(e){box.innerHTML='<small>Prezzi live</small><span>Provider non disponibile o chiave non valida</span>'}}
async function openDetail(id){let g=game(id);if(!g)return;if(g.rawgId)g=await hydrateRawg(g);const entry=library.find(x=>x.gameId===id),hero=steamHero(g),cover=steamCover(g),mockPrices=Object.entries(g.price||{}).map(([p,v])=>`<div><small>${p} · prezzo indicativo</small><b>${money(v)}</b></div>`).join('');$('#detail').style.setProperty('--game-gradient',grad(g));$('#detailContent').innerHTML=`<div class="detail-hero" style="${hero?`background-image:linear-gradient(90deg,#080a0fe8 0,#080a0f9e 48%,#080a0f25),linear-gradient(0deg,#0e1117 0,transparent 45%),url('${hero}')`:''}"><div class="detail-cover" style="--game-gradient:${grad(g)}">${cover?`<img src="${cover}" alt="Cover di ${g.title}" onerror="${imgFallback}">`:''}</div><div class="detail-hero-inner"><p class="eyebrow">${(g.genres||[]).join(' · ')}</p><h2>${g.title}</h2><div class="meta">${g.year||'TBA'} · ★ ${g.rating||'—'}/100</div></div></div><div class="detail-body"><div><p>${g.description||'Nessuna descrizione disponibile.'}</p><div class="actions">${entry?['In corso','Giocati','Da giocare'].map(s=>`<button class="${s===entry.status?'primary':''}" data-status="${s}">${s}</button>`).join(''):`<button class="primary" id="addLib">+ Aggiungi alla libreria</button>`}${entry?'<button id="removeLib">Rimuovi</button>':''}</div></div><div class="kv"><div><small>Sviluppatore</small>${g.developer||'—'}</div><div><small>Publisher</small>${g.publisher||'—'}</div><div><small>Piattaforme</small>${(g.platforms||[]).join(', ')||'—'}</div>${mockPrices}<div id="livePrice"><small>Prezzi live PC</small><span>Caricamento…</span></div></div></div>`;const dlg=$('#detail');dlg.showModal();loadLivePrice(g);if(entry){document.querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>{entry.status=b.dataset.status;save();dlg.close();render()});$('#removeLib').onclick=()=>{library=library.filter(x=>x!==entry);save();dlg.close();render()}}else $('#addLib').onclick=()=>{const p=(g.platforms||[]).map(normalizePlatform).find(x=>['PS5','Steam','Switch 2'].includes(x))||'Steam';library.push({gameId:id,platform:p,status:'Da giocare',snapshot:g.rawgId?g:undefined});save();dlg.close();render()}}
$('#closeDetail').onclick=()=>$('#detail').close();
search.oninput=()=>{if(view==='catalog'&&RawgService.enabled()){clearTimeout(searchTimer);searchTimer=setTimeout(()=>loadLiveCatalog(search.value.trim()),450)}else render()};[pf,sf].forEach(el=>el.oninput=render);
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelector('.nav.active')?.classList.remove('active');b.classList.add('active');view=b.dataset.view;$('#viewTitle').textContent=view==='catalog'?'Catalogo':view==='wishlist'?'Da giocare':'Bentornato, Simone';sf.style.display=view==='catalog'?'none':'';search.placeholder=view==='catalog'?'Cerca nel catalogo…':'Cerca nella tua collezione…';if(view==='catalog'&&RawgService.enabled())loadLiveCatalog(search.value.trim());else render()});
$('#settingsButton').onclick=()=>{$('#rawgKey').value=GameShelfConfig.rawgKey;$('#itadKey').value=GameShelfConfig.itadKey;$('#settings').showModal()};$('#closeSettings').onclick=()=>$('#settings').close();$('#saveSettings').onclick=()=>{GameShelfConfig.rawgKey=$('#rawgKey').value;GameShelfConfig.itadKey=$('#itadKey').value;$('#settingsStatus').textContent='Configurazione salvata su questo dispositivo.';if(view==='catalog'&&RawgService.enabled())loadLiveCatalog(search.value.trim());else render()};
render();